# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjCcrGW1SGVa3VTzNp21BCVhKgi2uvux
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df=pd.read_csv('uae_properties.csv')

df.head()

df['price'] = df['price'].astype(int)
df['rera']=df['rera'].astype('float')

df.info()

df.describe()

df.columns

df['city'] = df['displayAddress'].str.split(',').str[-1]

df

df.info()

# pd.options.display.float_format = '{:,.0f}'.format
df.groupby('bedrooms')['price'].mean()

table=pd.pivot_table(df,values='price',index='city',columns='bedrooms',aggfunc=['mean' , 'max' , 'sum' , 'min'])
table

# pd.options.display.float_format = '{:,.0f}'.format
df.groupby('bathrooms')['price'].mean()

df.groupby(['city', 'bedrooms']).agg(
    number_of_properties=('city', 'count'),
    total_price=('price', 'sum')
)

df[['price', 'bedrooms', 'bathrooms']].corr()
##"The dataset shows that all properties have 2 bathrooms. As a result, bathrooms do
##not contribute to the variation in property prices, and correlation with price cannot be computed."

df['area']=df['displayAddress'].str.split(',').str[-2]

df.groupby('area')['price'].mean().sort_values(ascending=False).head(10)

df.groupby('area').agg(
    number_of_properties=('area', 'count'),
    total_price=('price', 'sum')
).sort_values('total_price', ascending=False).head(10)

bins = [0, 500000, 1000000, 2000000, 5000000, 10000000]
labels = ['<500k','500k-1M','1M-2M','2M-5M','>5M']
df['price_range'] = pd.cut(df['price'], bins=bins, labels=labels)

df

price_city = pd.crosstab(df['city'], df['price_range'])
price_city

plt.figure(figsize=(10,6))
sns.boxplot(x='city', y='price', data=df)
plt.title('Price Distribution per City')
plt.xlabel('City')
plt.ylabel('Price (AED)')
plt.show()

plt.figure(figsize=(12,6))
sns.heatmap(city_bedrooms_price, annot=True, fmt=".0f", cmap="YlGnBu")
plt.title("Average Price per City and Bedrooms")
plt.xlabel("Bedrooms")
plt.ylabel("City")
plt.show()

top_areas = df.groupby('area')['price'].sum().sort_values(ascending=False).head(10)
top_areas.plot(kind='bar', figsize=(10,6), color='orange')
plt.title('Top 10 Areas by Total Property Value')
plt.xlabel('Area')
plt.ylabel('Total Price (AED)')
plt.show()

price_city.plot(kind='bar', stacked=True, figsize=(10,6), colormap='viridis')
plt.title("Properties per City by Price Range")
plt.xlabel("City")
plt.ylabel("Number of Properties")
plt.show()

bedrooms_city = pd.crosstab(df['city'], df['bedrooms'])
bedrooms_city.plot(kind='bar', stacked=True, figsize=(10,6), colormap='coolwarm')
plt.title("Distribution of Bedrooms per City")
plt.xlabel("City")
plt.ylabel("Number of Properties")
plt.show()

